version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      # Install Terraform
      - curl -O https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
      - unzip terraform_1.0.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      # Install AWS CLI
      - apt-get update && apt-get install -y python3-pip
      - pip3 install awscli
  build:
    commands:
      # Change to the Terraform directory
      - cd my-terraform-project
      # Initialize Terraform
      - terraform init
      # Apply the Terraform changes
      - echo "yes" | terraform apply
